services:

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 5050:80
    networks:
      - postgres-network
    depends_on:
      - postgres

  java:
    container_name: java
    image: maven:3.8.4-openjdk-17
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "mvn clean install && java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar target/Reservibe.jar"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - postgres-network
    depends_on:
      - postgres

networks:
  postgres-network:
    name: postgres-network