# Use a base image for pgAdmin
FROM dpage/pgadmin4

# Set environment variables
ENV PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
ENV PGADMIN_DEFAULT_PASSWORD=admin
ENV TZ=America/Sao_Paulo

# Expose the pgAdmin port
EXPOSE 5050