services:
  - type: web
    name: reservibe
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-crovi3g8fa8c73dq5se0-a:5432/reservibe
      - key: DATABASE_USER
        value: reservibe_user
      - key: DATABASE_PASSWORD
        value: e6Szg513GyrhXOPdAZ8nc15vbvO9LLOF
      - key: TZ
        value: America/Sao_Paulo

  - type: web
    name: pgadmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: pgadmin4@pgadmin.org
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
      - key: TZ
        value: America/Sao_Paulo