services:
  - type: web
    name: reservibe
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://postgres:5432/mydatabase
      - key: DATABASE_USER
        value: myuser
      - key: DATABASE_PASSWORD
        value: secret
      - key: TZ
        value: America/Sao_Paulo
    ports:
      - containerPort: 8080

  - type: web
    name: pgadmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: pgadmin4@pgadmin.org
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin
      - key: TZ
        value: America/Sao_Paulo
    ports:
      - containerPort: 5050