services:
  - type: web
    name: reservibe
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
      - key: DATABASE_USER
      - key: DATABASE_PASSWORD
      - key: TZ

  - type: web
    name: pgadmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
      - key: PGADMIN_DEFAULT_PASSWORD
      - key: TZ

fromGroup: reservibe-environment