services:
  - type: web
    name: reservibe
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: DATABASE_USER
        value: ${DATABASE_USER}
      - key: DATABASE_PASSWORD
        value: ${DATABASE_PASSWORD}
      - key: TZ
        value: America/Sao_Paulo

  - type: web
    name: pgadmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.pgadmin
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: ${PGADMIN_DEFAULT_EMAIL}
      - key: PGADMIN_DEFAULT_PASSWORD
        value: ${PGADMIN_DEFAULT_PASSWORD}
      - key: TZ
        value: America/Sao_Paulo