envVarGroups:
  - name: reservibe-environment

services:
  - type: web
    name: reservibe
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - fromGroup: reservibe-environment

  - type: web
    name: pgadmin
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.pgadmin
    envVars:
      - fromGroup: reservibe-environment